import type { Metadata } from "next";
import "./globals.css";
import { SnackbarProvider, useSnackbar } from "notistack";
import { Providers } from "./providers";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className="bg-blackBg text-white">
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
